services:
    jobeet.admin.category:
        class: AppBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Categories }
        arguments:
            - ~
            - AppBundle\Entity\Category
            - 'AppBundle:CategoryAdmin'

    jobeet.admin.job:
        class: AppBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Jobs }
        arguments:
            - ~
            - AppBundle\Entity\Job
            - 'AppBundle:JobAdmin'

    jobeet.admin.affiliate:
            class: AppBundle\Admin\AffiliateAdmin
            tags:
                - { name: sonata.admin, manager_type: orm, group: jobeet, label: Affiliates }
            arguments:
                - ~
                - AppBundle\Entity\Affiliate
                - 'AppBundle:AffiliateAdmin'
